- hosts: all
  tasks:
  - name: Install python
    include_tasks: python36.yml
    
  - name: install git
    yum:
      name: 
      - git 
  
  - name: Git clone
    shell: 'cd /tmp && git clone https://github.com/anfederico/Flaskex'
    args:
      creates: /tmp/Flaskex 
  
  - name: install requirements
    shell: 'cd /tmp/Flaskex && pip3 install -r requirements.txt'
     
  - name: Run app
    args:
      chdir: /tmp/Flaskex
    shell: 'nohup python3 app.py &' 
  
   
  
    