- hosts: all
  tasks:
  - name: Install python
    include_tasks: python36.yml
    
  - name: install git
    yum:
      name: 
      - git
      - python-pip
  
  - name: upgrade pip
    shell: pip install --upgrade pip
    
    
  
  - name: Git clone
    shell: 'cd /tmp && git clone https://github.com/anfederico/Flaskex'
    args:
      creates: Flaskex 
  
  - name: install requirements
    shell: 'cd /tmp/Flaskex && pip install -r requirements.txt'
    
   
  - name: Run app
    args:
      chdir: /tmp/Flaskex
    shell: python app.py 
  
   
  
    